### ISSUE TITLE
장소 투표에 투표 후 재접속 시 places 목록 갱신 안됨

### ISSUE THREAD

**Issue by junepil** [ksg1227/NetworkProgramming_teamProject#11]
# What's wrong?
현재 코드 상으로는 vote 기능에 접속하면 현재까지 제시된 장소 목록을 볼 수 있게 되어있으나

1. 장소 투표를 수행
2. 장소 추가
3. 장소 투표에 재접속 시 1.이후에 제시된 장소들은 미표시

> 새로운 클라이언트가 접속해서 투표 기능에 접속했을 때는 이후에 제시된 장소들이 정상적으로 보임

_Originally posted by @ksg1227 in https://github.com/ksg1227/NetworkProgramming_teamProject/issues/10#issuecomment-2492922420_

**Comment by ksg1227** [comment]
아 추가로 vote 기능에 접속하고 정상적으로 투표를 한 경우가 아니라, 이미 존재하는 장소에 투표해서 누락되거나 하는 경우에도 동일한 문제가 발생했습니다

**Comment by junepil** [comment]
진짜 이상하네요 서버 측에서 보낼 때는 장소가 4개가 들어 있어도, 클라이언트 측이 받는 장소는 3개예요
### 서버에서 전달하는 `places`
<img width="1512" alt="image" src="https://github.com/user-attachments/assets/943609f8-adcd-4abf-963b-caae85ebdc45">

### 클라이언트에서 받는 `places`
<img width="1512" alt="image" src="https://github.com/user-attachments/assets/9d065e73-2c1d-40a3-a13d-50d844b1c9e1">

**Comment by ksg1227** [comment]
맞아요 저도 아까 디버그해보니까 진짜 이상하더라구요..

근데 더 이상한 건 
1. 존재하지 않는 장소애 투표해서 오류 메세지 출력
2. 새로운 장소 제시 (현쟈 클라이언트, 다른 클라이언트 누구든지 상관 x)
3. 투표 기능 재접속
4. 목록에 새로 제시된 장소 안뜸
5. 근데 2. 에서 제시한 장소 이름을 명시하면 투표는 성공적으로 됨

이렇게 동작하더라구요

**Comment by ksg1227** [comment]
와 해결했어요!!

<img width="524" alt="스크린샷 2024-11-23 오전 1 07 47" src="https://github.com/user-attachments/assets/82b43b3a-1c05-4313-9668-baa133952766">

getPlaces()를 수행할 때 매번 복사본을 반환하면 해결되네요... 

한 번 저렇게 코드 변경하고 테스트해보시겠어요? 

@hanu9257

**Comment by junepil** [comment]
이..이게 대체 무슨 일이죠 ㅠㅠㅠㅠ감사하면서도 진짜 버그가 너무 어이없네요 🫠

**Comment by ksg1227** [comment]
static + 참조 전달 의 미친 콜라보레이션인 것 같아요... 그래도 우선 해결돼서 다행입니다!

**Comment by ksg1227** [comment]
괜찮으시다면 그 장소 제시 기능에 접속했을 때, 현재까지 제시된 장소들을 보여주는 기능도 있으면 좋을 것 같은데 부탁드려도될까요?

**Comment by junepil** [comment]
아 네네 알겠습니다 기능 추가해서 PR에 넣어놓을게요
